# ==============
# Shell Defaults
# ==============

# include binaries from $HOME/bin. To add more, link them in $HOME/bin/
PATH=$PATH:$HOME/opt/bin
PATH=$PATH:/opt/local/bin
export PATH


# global bash completion
[[ -s /etc/bash_completion ]] && source /etc/bash_completion
[[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"

# tweak history
export HISTCONTROL=ignoreboth
export HISTSIZE=9999
export HISTIGNORE="ls:la:l:cd:pwd:clear:history:jobs:fg:bg:pushd*:popd*:g s:g d:g l"

# disable beep
# [[ $TERM != "dumb" ]] && setterm -blength 0

# load everything from $HOME/.bash/ except README.md and directories
if [[ -d $HOME/.bash/ ]]; then
    for f in $HOME/.bash/*; do
        [[ $f == *README.md* ]] && continue
        [[ -d $f ]] && continue
        source $f
    done
fi

# set vim as default editor
vim=/usr/bin/vim
export EDITOR=$vim
export VISUAL=$vim

export PATH="/usr/local/opt/python/libexec/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(hcloud completion bash)"

export LC_ALL=C

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
